### ISSUE TITLE
Dashboard error with 1.2.5 update

### ISSUE THREAD

**Issue by JayBox325** [riasvdv/craft-colour-swatches#28]
I've just updated to 1.2.5 (thanks for being so quick at getting back to me today 🙌🏻) and I'm getting a `Variable "value" does not exist.` error at the root level of my admin view (`/admin/dashboard`).

See below for more:

```
Twig\Error\RuntimeError: Variable "value" does not exist. in /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/rias/craft-colour-swatches/src/templates/input.twig:29
Stack trace:
#0 /Users/jaycollett/Sites/jaycollett/project-name/build/storage/runtime/compiled_templates/78/78d3264ed9e7d671ddd08acce375d70fc13b05899ac65adb26bb1eff206f24de.php(84): __TwigTemplate_a4d73b6ecc9488d2205d4146a0a48ad5e10bee0383a66686b4e392fc01c13b4e->{closure}()
#1 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_a4d73b6ecc9488d2205d4146a0a48ad5e10bee0383a66686b4e392fc01c13b4e->doDisplay(Array, Array)
#2 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#3 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#4 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#5 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#6 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/web/View.php(400): Twig\Environment->render('colour-swatches...', Array)
#7 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/rias/craft-colour-swatches/src/fields/ColourSwatches.php(205): craft\web\View->renderTemplate('colour-swatches...', Array)
#8 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Extension/CoreExtension.php(1495): rias\colourswatches\fields\ColourSwatches->getInputHtml(Object(rias\colourswatches\models\ColourSwatches), Object(craft\elements\MatrixBlock))
#9 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/helpers/Template.php(105): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(rias\colourswatches\fields\ColourSwatches), 'getInputHtml', Array, 'method', false, false)
#10 /Users/jaycollett/Sites/jaycollett/project-name/build/storage/runtime/compiled_templates/31/31b9c922b134031893aed3d18850ebb21106eed6bd0988c1418525f062b94216.php(78): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(rias\colourswatches\fields\ColourSwatches), 'getInputHtml', Array, 'method')
#11 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_325d47befe23fcb8c0737038f2a4d2d17501159ec9613fbcdd1913df28e624a2->doDisplay(Array, Array)
#12 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#13 /Users/jaycollett/Sites/jaycollett/project-name/build/storage/runtime/compiled_templates/01/01c043e455977953969ef2f83396173db38eb8c62d67770a564c0dcd460a8dbd.php(86): Twig\Template->display(Array)
#14 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_9a037541dd0bf928cb87edbf20e8fedb65d3a22bc5ee47c05fc28df8a5021042->doDisplay(Array, Array)
#15 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#17 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#18 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#19 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/web/View.php(400): Twig\Environment->render('_includes/field...', Array)
#20 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/fields/Matrix.php(1107): craft\web\View->renderTemplate('_includes/field...', Array)
#21 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/fields/Matrix.php(647): craft\fields\Matrix->_getBlockTypeInfoForInput(NULL, Array)
#22 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Extension/CoreExtension.php(1495): craft\fields\Matrix->getInputHtml(Array, NULL)
#23 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/helpers/Template.php(105): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\fields\Matrix), 'getInputHtml', Array, 'method', false, false)
#24 /Users/jaycollett/Sites/jaycollett/project-name/build/storage/runtime/compiled_templates/31/31b9c922b134031893aed3d18850ebb21106eed6bd0988c1418525f062b94216.php(78): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\fields\Matrix), 'getInputHtml', Array, 'method')
#25 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_325d47befe23fcb8c0737038f2a4d2d17501159ec9613fbcdd1913df28e624a2->doDisplay(Array, Array)
#26 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#27 /Users/jaycollett/Sites/jaycollett/project-name/build/storage/runtime/compiled_templates/07/078714ee4a9cb9d0a9575b2a834c5749af5ef76d8d9ee96c02449942fabb5e99.php(86): Twig\Template->display(Array)
#28 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_b17d6750c1fece166e262fb06bc5bad86bcf4175b27b347493a1c20c6219d8ca->doDisplay(Array, Array)
#29 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#30 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#31 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#32 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#33 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/web/View.php(400): Twig\Environment->render('_components/wid...', Array)
#34 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/widgets/QuickPost.php(177): craft\web\View->renderTemplate('_components/wid...', Array)
#35 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/controllers/DashboardController.php(514): craft\widgets\QuickPost->getBodyHtml()
#36 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/controllers/DashboardController.php(99): craft\controllers\DashboardController->_getWidgetInfo(Object(craft\widgets\QuickPost))
#37 [internal function]: craft\controllers\DashboardController->actionIndex()
#38 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#39 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#40 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('index', Array)
#41 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#42 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('dashboard/index', Array)
#43 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('dashboard/index', Array)
#44 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#45 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#46 /Users/jaycollett/Sites/jaycollett/project-name/build/public/index.php(21): yii\base\Application->run()
#47 {main}
```

Here's an easier screenshot of the markup it's failing on:

![Screenshot 2019-12-18 at 15 22 48](https://user-images.githubusercontent.com/13233809/71098872-4be9ec80-21aa-11ea-9d28-b0146c4d03f4.png)

Thanks!

**Comment by riasvdv** [comment]
Yep, copy paste mistake, try updating to 1.2.6

**Comment by JayBox325** [comment]
That got it. You're a lifesaver. Great plugin, btw! 👏🏻
